<a href="https://colab.research.google.com/github/suryakant49/mini-project/blob/main/MINI_PROJECT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install bing-image-downloader

In [2]:
import bing_image_downloader

In [3]:
!mkdir images

In [4]:
cd /content/

/content


In [5]:
from bing_image_downloader import downloader
downloader.download('black panther animal', limit=30, output_dir='images', adult_filter_off=True, force_replace=False, timeout=60)



[!!]Indexing page: 1

[%] Indexed 30 Images on Page 1.


[%] Downloading Image #1 from https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Jaguar.jpg/1200px-Jaguar.jpg
[%] File Downloaded !

[%] Downloading Image #2 from https://media.londolozi.com/wp-content/uploads/2016/07/11013916/Panther1.jpg
[%] File Downloaded !

[%] Downloading Image #3 from https://news.nationalgeographic.com/content/dam/news/photos/000/878/87871.ngsversion.1459551629354.adapt.1900.1.jpg
[!] Issue getting: https://news.nationalgeographic.com/content/dam/news/photos/000/878/87871.ngsversion.1459551629354.adapt.1900.1.jpg
[!] Error:: The read operation timed out
[%] Downloading Image #3 from https://wallpapercave.com/wp/wp2515181.jpg
[%] File Downloaded !

[%] Downloading Image #4 from http://1.bp.blogspot.com/-nw0v7OqTnA0/T7kkC5KalPI/AAAAAAAAVAc/VLQXz09buFg/s1600/Black-Panther-Animal-Wallpaper.jpg
[%] File Downloaded !

[%] Downloading Image #5 from http://4.bp.blogspot.com/-j8EI0QsQHbA/T7kkBwc1jUI/AAAAA

In [6]:
from bing_image_downloader import downloader
downloader.download('black cat', limit=30, output_dir='images', adult_filter_off=True, force_replace=False, timeout=60)




[!!]Indexing page: 1

[%] Indexed 30 Images on Page 1.


[%] Downloading Image #1 from https://img.huffingtonpost.com/asset/582cb2601a00002400cc8426.jpeg?cache=wltod2kvw5&amp;ops=1910_1000
[Error]Invalid image, not saving https://img.huffingtonpost.com/asset/582cb2601a00002400cc8426.jpeg?cache=wltod2kvw5&amp;ops=1910_1000

[!] Issue getting: https://img.huffingtonpost.com/asset/582cb2601a00002400cc8426.jpeg?cache=wltod2kvw5&amp;ops=1910_1000
[!] Error:: No active exception to reraise
[%] Downloading Image #1 from https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Close_up_of_a_black_domestic_cat.jpg/1200px-Close_up_of_a_black_domestic_cat.jpg
[Error]Invalid image, not saving https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Close_up_of_a_black_domestic_cat.jpg/1200px-Close_up_of_a_black_domestic_cat.jpg

[!] Issue getting: https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Close_up_of_a_black_domestic_cat.jpg/1200px-Close_up_of_a_black_domestic_cat.jpg
[!] Error

In [7]:
import numpy as np
from skimage.transform import resize
from skimage.io import imread
import matplotlib.pyplot as plt
import os
import pandas as pd

target = []
images = []
flat_data = []

DATADIR = '/content/images'
CATEGORIES = ['black cat','black panther animal']

for category in CATEGORIES:
  class_num = CATEGORIES.index(category)
  path = os.path.join(DATADIR,category)
  for img in os.listdir(path):
    img_array = imread(os.path.join(path,img))
    img_resized = resize(img_array,(150,150,3))
    flat_data.append(img_resized.flatten())
    images.append(img_resized)
    target.append(class_num)


In [8]:
target = np.array(target)
images = np.array(images)
flat_data = np.array(flat_data)


In [9]:
df = pd.DataFrame(flat_data)
df['Target'] = target
df.head()


0         1         2         3  ...     67497     67498     67499  Target
0  0.211765  0.156863  0.129412  0.169503  ...  0.203922  0.176471  0.137255       0
1  0.832026  0.800000  0.768627  0.835294  ...  0.988235  0.984314  0.972549       0
2  0.000000  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000       0
3  0.326031  0.365900  0.254693  0.675817  ...  0.094662  0.061961  0.034876       0
4  0.498039  0.152941  0.047059  0.521673  ...  0.192157  0.137429  0.105264       0

[5 rows x 67501 columns]

In [10]:
# applying logistic regression model
x = df.iloc[:,0:67500]
y = df.iloc[:,67500]


In [11]:
#creating training and testing data

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3)


In [12]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(x_train,y_train)
predict = model.predict(x_test)


In [13]:
from sklearn.metrics import confusion_matrix,accuracy_score
print(confusion_matrix(y_test,predict))
print('accuracy_score is:',accuracy_score(y_test,predict))

[[7 4]
 [0 7]]
accuracy_score is: 0.7777777777777778


In [ ]:
## for calculating the suitable value of K

import numpy as np
from sklearn.model_selection import cross_val_score
cross_valid_score = []

for k in range(1,55):
  knn = KNeighborsClassifier(n_neighbors=k)
  scores = cross_val_score(knn,x,y,cv=10,scoring='accuracy')
  cross_valid_score.append(scores.mean())
print('optimal value of K is:' ,np.argmax(cross_valid_score))

In [18]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=33)
model.fit(x_train,y_train)
pred = model.predict(x_test)

In [19]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
#confusion_matrix(pred,y_test)
print(confusion_matrix(y_test,pred))
print(accuracy_score(pred,y_test))

[[2 9]
 [0 7]]
0.5


In [17]:
print(confusion_matrix(y_test,predict))
print('Accuracy score of Logistic Regression is:',accuracy_score(y_test,predict))
print(confusion_matrix(y_test,pred))
print('Accuracy Score for KNN model:',accuracy_score(y_test,pred))

[[7 4]
 [0 7]]
Accuracy score of Logistic Regression is: 0.7777777777777778
[[2 9]
 [0 7]]
Accuracy Score for KNN model: 0.5
